config/routes.rb
Rails.application.routes.draw do

root                   'static_pages#home'
get    'about'    =>   'static_pages#about'
get    'places'   =>   'static_pages#places'
get    'signup'   =>   'users#new'
get    'login'    =>   'sessions#new'
post   'login'    =>   'sessions#create'
delete 'logout'   =>   'sessions#destroy'
resources :users

end

app/models/place.rb
class Place < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base

  before_save {self.email = email.downcase }
  validates :firstname, presence: true, length: { maximum: 50 }
  validates :lastname,  presence: true, length: { maximum: 50 }
  validates :username,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email,     presence: true, length: { maximum: 50 },
                        format: { with: VALID_EMAIL_REGEX },
                        uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password,  presence: true, length: { minimum: 6 }, allow_nil: true

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  def index
    @places = Place.all
  end

  def show

  end

  def edit

  end

  def new

  end

  def create

  end

  def update

  end

  def destroy

  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :owned_posts, only: [:edit, :update, :destroy]
  def index
    @posts = Posts.all
  end

  def show

  end

  def edit

  end

  def new
    @post = current_user.posts.build
  end

  def create

  end

  def update

  end

  def destroy

  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # Log the user in and redirect to the user's show page.
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination' # Not quite right!
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_path
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home

  end

  def about

  end

  def places

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :logged_in_user, only: [:edit, :update]
before_action :correct_user,   only: [:edit, :update]


def new
  @user = User.new
end

def show
  @user = User.find(params[:id])
end

def create
  @user = User.new(user_params)
  if @user.save
    log_in @user
    flash[:success] = "Welcome to the Travel List"
    redirect_to @user
  else
    render 'new'
  end
end

def edit
  @user = User.find(params[:id])
end

def update
  @user = User.find(params[:id])
  if@user.update_attributes(user_params)
    flash[:success] = "Changes saved successfully"
    redirect_to @user
  else
    render 'edit'
  end
end

private
  def user_params
    params.require(:user).permit(:firstname, :lastname, :username, :email, :password, :password_confirmation)
  end

  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_path) unless current_user?(@user)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user?(user)
    user == current_user
  end
  # Returns the current logged-in user
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  # Redirects to stored location (or to the default).
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.url if request.get?
  end

  # Logs out the current user
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar for the given user
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.username, class: "gravatar")
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bucketlist</title>

  <link href='https://fonts.googleapis.com/css?family=Shadows+Into+Light' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Poiret+One' rel='stylesheet' type='text/css'>
    <!--Let browser know website is optimized for mobile-->
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body
  <% if current_page?(controller: 'static_pages', action: 'home') %>
    class="homepage"
  <% end %>
>
<%= render "shared/navbar" %>

<%= yield %>
<%= render "shared/footer" %>

</body>
</html>

app/views/posts/_form.html.erb
<div class="form-wrapper"></div>
<%= simple_form_for @post, html: { class: 'form-horizontal', multipart: true } do |f| %>
  <div class="form-group">
    <%= f.input :image %>
  </div>
  <div class="form-group text-center">
    <%= f.input :caption %>
  </div>
  <div class="form-group text-center">
    <%= f.button :submit, class: 'btn-success' %>
  </div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>
        <%= msg %>
      </li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
  <!-- copyright stuffs.. -->
<nav class="navbar navbar-inverse navbar-fixed-bottom">
  <footer class="text-center">Copyright&copy 2015 <a href="http://www.reactiveventur.es" target="_blank" class="link">Travel List</a></footer>
</nav>

app/views/shared/_navbar.html.erb
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".nav-collapse" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Free Spirit</a>
      </div><!-- navbar-header -->

      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home",      root_path%></li>
          <li><%= link_to "About",     about_path%></li>
          <li><%= link_to "Places",    places_path%></li>
          <% if logged_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Log out", logout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Log in", login_path %></li>
          <% end %>
        </ul>
      </div><!-- nav-collapse -->
    </div><!-- container-fluid -->
  </nav><!-- navbar -->

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1 class="about-header">About</h1>

<p class="col-sm-4 col-md-6 col-sm-offset-4 col-md-offset-3">
  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Necessitatibus, saepe! Reprehenderit placeat, dicta vero hic saepe itaque voluptates eveniet minus tempore, distinctio amet quae sunt odio, doloremque, cupiditate omnis. Ut.
</p>

app/views/static_pages/home.html.erb
<h1 class="home">Adventure Awaits</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="input-group">
      <input type="text" class="form-control" placeholder="Search location...">
      <span class="input-group-btn">
        <button class="btn btn-default" type="button">Go!</button>
      </span>
    </div><!-- /input-group -->
  </div><!-- /.col-lg-6 -->
</div><!-- /.row -->

app/views/static_pages/places.html.erb
<h1 class="places-title">Places</h1>

<div id="picture-grid">
  <div class="row">
    <div class="places"><%= image_tag("chiang-mai-thailand.jpg", :alt => "Chiang Mai", class: "img-responsive") %></div>
    <div class="places"><%= image_tag("chiang-mai-thailand.jpg", :alt => "Chiang Mai", class: "img-responsive") %></div>
    <div class="places"><%= image_tag("chiang-mai-thailand.jpg", :alt => "Chiang Mai", class: "img-responsive") %></div>
  </div>
  <div class="row">
    <div class="places"><%= image_tag("chiang-mai-thailand.jpg", :alt => "Chiang Mai", class: "img-responsive") %></div>
    <div class="places"><%= image_tag("chiang-mai-thailand.jpg", :alt => "Chiang Mai", class: "img-responsive") %></div>
    <div class="places"><%= image_tag("chiang-mai-thailand.jpg", :alt => "Chiang Mai", class: "img-responsive") %></div>
  </div>
  <div class="row">
    <div class="places"><%= image_tag("chiang-mai-thailand.jpg", :alt => "Chiang Mai", class: "img-responsive") %></div>
    <div class="places"><%= image_tag("chiang-mai-thailand.jpg", :alt => "Chiang Mai", class: "img-responsive") %></div>
    <div class="places"><%= image_tag("chiang-mai-thailand.jpg", :alt => "Chiang Mai", class: "img-responsive") %></div>
  </div>
</div>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>


<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
      <div class="gravatar_edit">
        <%= gravatar_for @user %>
        <a href="http://gravatar.com/emails" target="_blank">change</a>
      </div>
      <%= form_for(@user) do |f| %>
        <%= render "shared/error_messages" %>
        <h2>Edit your Profile</h2>
        <div class="row">
          <div class="col-xs-6 col-sm-6 col-md-6">
            <div class="form-group">
              <%= f.label :firstname %>
              <%= f.text_field :firstname, class: "form-control" %>
            </div>
          </div>
          <div class="col-xs-6 col-sm-6 col-md-6">
            <div class="form-group">
              <%= f.label :lastname %>
              <%= f.text_field :lastname, class: "form-control" %>
            </div>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :username %>
          <%= f.text_field :username, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :email %>
          <%= f.email_field :email, class: "form-control" %>
        </div>
        <div class="row">
          <div class="col-xs-6 col-sm-6 col-md-6">
            <div class="form-group">
              <%= f.label :password %>
              <%= f.password_field :password, class: "form-control" %>
            </div>
          </div>
          <div class="col-xs-6 col-sm-6 col-md-6">
            <div class="form-group">
              <%= f.label :password_confirmation, "Password Confirmation" %>
              <%= f.password_field :password_confirmation, class: "form-control" %>
            </div>
          </div>
        </div>
          <%= f.submit "Save Changes", class: "btn btn-primary btn-block btn-lg col-xs-4 col-md-4" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign Up') %>


<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
      <%= form_for(@user) do |f| %>
        <%= render "shared/error_messages" %>
        <h2>Sign Up</h2>
        <div class="row">
          <div class="col-xs-6 col-sm-6 col-md-6">
            <div class="form-group">
              <%= f.label :firstname %>
              <%= f.text_field :firstname, class: "form-control" %>
            </div>
          </div>
          <div class="col-xs-6 col-sm-6 col-md-6">
            <div class="form-group">
              <%= f.label :lastname %>
              <%= f.text_field :lastname, class: "form-control" %>
            </div>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :username %>
          <%= f.text_field :username, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :email %>
          <%= f.email_field :email, class: "form-control" %>
        </div>
        <div class="row">
          <div class="col-xs-6 col-sm-6 col-md-6">
            <div class="form-group">
              <%= f.label :password %>
              <%= f.password_field :password, class: "form-control" %>
            </div>
          </div>
          <div class="col-xs-6 col-sm-6 col-md-6">
            <div class="form-group">
              <%= f.label :password_confirmation, "Password Confirmation" %>
              <%= f.password_field :password_confirmation, class: "form-control" %>
            </div>
          </div>
        </div>


          <%= f.submit "Register", class: "btn btn-primary btn-block btn-lg col-xs-4 col-md-4" %>
          <%= f.submit "Sign In", class: "btn btn-success btn-block btn-lg col-xs-4 col-md-4" %>

      <% end %>
    </div>
  </div>
</div>


<!-- button styling

<div class="col-xs-6 col-md-6"><input type="submit" value="Register" class="btn btn-primary btn-block btn-lg" tabindex="7"></div>
<div class="col-xs-6 col-md-6"><a href="#" class="btn btn-success btn-block btn-lg">Sign In</a></div>

-->

app/views/users/show.html.erb
<% provide(:title, @user.username) %>

<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.firstname %> <%= @user.lastname %>
      </h1>
      <h4><%= @user.username %></h4>
    </section>
  </aside>
</div>